permalink: /:categories/:year/:month/:day/:title/

collections:
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed

feed:
  path: feed.xml
  collections:
    - posts